export const stuidoLayoutsMock = [
  {
    FacilityStudioLayoutId: 471,
    FacilityId: "456",
    StudioId: 104,
    SortOrder: 1,
    LayoutName: "Cycling Studio",
    LayoutTypeId: 1,
    LayoutTypeName: "Bike",
    IsActive: true,
    StudioName: "Cycling Studio"
  },
  {
    FacilityStudioLayoutId: 472,
    FacilityId: "456",
    StudioId: 109,
    SortOrder: 1,
    LayoutName: "Precision run",
    LayoutTypeId: 2,
    LayoutTypeName: "Treadmill",
    IsActive: true,
    StudioName: "Treadmill Area"
  }
];

export const layoutInfoMock = {
  ClubId: 0,
  ClubName: null,
  LayoutTypeName: "Bike",
  Result: [
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 56,
      StudioGridX: 672,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14207,
      IsActive: true,
      IsDisabled: true,
      LocalId: 1,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "62723",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 56,
      StudioGridX: 616,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14208,
      IsActive: true,
      IsDisabled: true,
      LocalId: 2,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "38143",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 616,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14209,
      IsActive: true,
      IsDisabled: false,
      LocalId: 3,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "43096",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 560,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14210,
      IsActive: true,
      IsDisabled: false,
      LocalId: 4,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "31130",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 504,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14211,
      IsActive: true,
      IsDisabled: false,
      LocalId: 5,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "36257",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 448,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14212,
      IsActive: true,
      IsDisabled: false,
      LocalId: 6,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "18180",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 336,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14213,
      IsActive: true,
      IsDisabled: true,
      LocalId: 7,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "41151",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 280,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14214,
      IsActive: true,
      IsDisabled: false,
      LocalId: 8,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "21601",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 224,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14215,
      IsActive: true,
      IsDisabled: false,
      LocalId: 9,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "28253",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 168,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14216,
      IsActive: true,
      IsDisabled: false,
      LocalId: 10,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "10736",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 56,
      StudioGridX: 168,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14217,
      IsActive: true,
      IsDisabled: false,
      LocalId: 11,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "43664",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 56,
      StudioGridX: 112,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14218,
      IsActive: true,
      IsDisabled: false,
      LocalId: 12,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "44300",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 56,
      StudioGridX: 784,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14219,
      IsActive: true,
      IsDisabled: false,
      LocalId: 13,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "30597",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 784,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14220,
      IsActive: true,
      IsDisabled: false,
      LocalId: 14,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "25028",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 168,
      StudioGridX: 728,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14221,
      IsActive: true,
      IsDisabled: false,
      LocalId: 15,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "39317",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 672,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14222,
      IsActive: true,
      IsDisabled: false,
      LocalId: 16,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "23338",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 616,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14223,
      IsActive: true,
      IsDisabled: false,
      LocalId: 17,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "54433",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 560,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14224,
      IsActive: true,
      IsDisabled: true,
      LocalId: 18,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "35242",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 504,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14225,
      IsActive: true,
      IsDisabled: false,
      LocalId: 19,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "14358",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 448,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14226,
      IsActive: true,
      IsDisabled: true,
      LocalId: 20,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "39445",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 336,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14227,
      IsActive: true,
      IsDisabled: false,
      LocalId: 21,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "35794",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 280,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14228,
      IsActive: true,
      IsDisabled: false,
      LocalId: 22,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "48628",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 224,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14229,
      IsActive: true,
      IsDisabled: false,
      LocalId: 23,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "53191",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 168,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14230,
      IsActive: true,
      IsDisabled: false,
      LocalId: 24,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "16253",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 224,
      StudioGridX: 112,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14231,
      IsActive: true,
      IsDisabled: false,
      LocalId: 25,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "45032",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 168,
      StudioGridX: 56,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14232,
      IsActive: true,
      IsDisabled: false,
      LocalId: 26,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "55463",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 112,
      StudioGridX: 0,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14233,
      IsActive: true,
      IsDisabled: false,
      LocalId: 27,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "23513",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 56,
      StudioGridX: 0,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14234,
      IsActive: true,
      IsDisabled: false,
      LocalId: 28,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "30697",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 280,
      StudioGridX: 784,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14235,
      IsActive: true,
      IsDisabled: false,
      LocalId: 29,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "43241",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 728,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14236,
      IsActive: true,
      IsDisabled: false,
      LocalId: 30,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "50302",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 672,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14237,
      IsActive: true,
      IsDisabled: false,
      LocalId: 31,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "33",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 616,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14238,
      IsActive: true,
      IsDisabled: false,
      LocalId: 32,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "17915",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 560,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14239,
      IsActive: true,
      IsDisabled: false,
      LocalId: 33,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "25235",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 504,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14240,
      IsActive: true,
      IsDisabled: false,
      LocalId: 34,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "26659",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 280,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14241,
      IsActive: true,
      IsDisabled: false,
      LocalId: 35,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "38962",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 224,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14242,
      IsActive: true,
      IsDisabled: false,
      LocalId: 36,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "12234",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 168,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14243,
      IsActive: true,
      IsDisabled: true,
      LocalId: 37,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "9",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 112,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14244,
      IsActive: true,
      IsDisabled: true,
      LocalId: 38,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "4",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 336,
      StudioGridX: 56,
      GridItemTypeId: 1,
      GridItemType: "Bike",
      HasDeviceId: true,
      IsReservable: true,
      ReservableEquipmentId: 14245,
      IsActive: true,
      IsDisabled: false,
      LocalId: 39,
      EquipmentName: "Bike",
      ReservationId: null,
      Reserved: false,
      DeviceId: "45368",
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 0,
      StudioGridX: 392,
      GridItemTypeId: 2,
      GridItemType: "Instructor",
      HasDeviceId: false,
      IsReservable: false,
      ReservableEquipmentId: null,
      IsActive: false,
      IsDisabled: null,
      LocalId: null,
      EquipmentName: null,
      ReservationId: null,
      Reserved: false,
      DeviceId: null,
      IsReservedForEntity: false
    },
    {
      ClubId: 0,
      FacilityId: "456",
      StudioId: 104,
      StudioGridY: 448,
      StudioGridX: 392,
      GridItemTypeId: 5,
      GridItemType: "Door - Bottom Left",
      HasDeviceId: false,
      IsReservable: false,
      ReservableEquipmentId: null,
      IsActive: false,
      IsDisabled: null,
      LocalId: null,
      EquipmentName: null,
      ReservationId: null,
      Reserved: false,
      DeviceId: null,
      IsReservedForEntity: false
    }
  ],
  FacilityId: "456",
  StudioId: 104,
  StudioName: "Cycling Studio",
  StudioWidth: 925,
  StudioHeight: 475,
  FacilityStudioLayoutId: 471,
  SortOrder: 1,
  LayoutName: "Cycling Studio",
  LayoutTypeId: 1,
  SpotReservedForHotelLimit: 0,
  Success: true,
  ResponseMessage: null
};
